"""One-shot generator: parse Avogadro's elementdata.h -> molom/core/elements.py.

Not shipped with MoloM; kept in the scratchpad. Re-run if Avogadro's data file
is ever re-imported.
"""
import re
import sys
import textwrap

SRC = sys.argv[1]
DST = sys.argv[2]

text = open(SRC, "r", encoding="utf-8").read()


def array_body(name):
    m = re.search(re.escape(name) + r"\[[^\]]*\](?:\[\d+\])?\s*=\s*\{", text)
    if not m:
        raise SystemExit("array not found: " + name)
    start = m.end()
    depth = 1
    i = start
    while depth:
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    return text[start:i - 1]


def strip_comments(s):
    return re.sub(r"//[^\n]*", "", s)


def parse_strings(body):
    return re.findall(r'"([^"]*)"', body)


def parse_floats(body):
    return [float(t) for t in re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?",
                                         strip_comments(body))]


def parse_colors(body):
    trips = re.findall(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}", strip_comments(body))
    return [(int(r), int(g), int(b)) for r, g, b in trips]


symbols = parse_strings(array_body("element_symbols"))
names = parse_strings(array_body("element_names"))
masses = parse_floats(array_body("element_masses"))
vdw = parse_floats(array_body("element_VDW"))
cov = parse_floats(array_body("element_covalent"))
colors = parse_colors(array_body("element_color"))

n = len(symbols)
assert n == 119, n
for arr, nm in ((names, "names"), (masses, "masses"), (vdw, "vdw"),
                (cov, "cov"), (colors, "colors")):
    assert len(arr) == n, (nm, len(arr))

# Sanity anchors (values quoted in the header's comments / known chemistry)
assert symbols[1] == "H" and symbols[6] == "C" and symbols[118] == "Og"
assert abs(vdw[1] - 1.2) < 1e-9 and abs(cov[6] - 0.75) < 1e-9
assert colors[1] == (240, 240, 240) and colors[6] == (127, 127, 127)


def fmt_tuple_lines(items, per_line, indent="    "):
    out, line = [], []
    for it in items:
        line.append(it)
        if len(line) == per_line:
            out.append(indent + " ".join(line))
            line = []
    if line:
        out.append(indent + " ".join(line))
    return "\n".join(out)


sym_items = ['"%s",' % s for s in symbols]
name_items = ['"%s",' % s for s in names]
mass_items = ["%r," % m for m in masses]
vdw_items = ["%r," % v for v in vdw]
cov_items = ["%r," % c for c in cov]
col_items = ["(%d, %d, %d)," % c for c in colors]

py = '''\
"""Element data, transcoded from Avogadro 2's avogadro/core/elementdata.h.

Index = atomic number; index 0 is the "Xx" dummy atom. 119 entries (Xx + H..Og).

Provenance (BSD 3-Clause, Copyright 2011-2020 Kitware, Inc. - see
THIRD_PARTY_NOTICES.md):
  https://github.com/OpenChemistry/avogadrolibs  avogadro/core/elementdata.h
- RADII_VDW:      Alvarez, Dalton Trans. 2013, 42, 8617 (doi:10.1039/C3DT50599E)
- RADII_COVALENT: Pyykko & Atsumi, Chem. Eur. J. 2009 (doi:10.1002/chem.200800987)
- COLORS: Jmol/CPK scheme with Avogadro's tweaks (H off-white for light
  backgrounds, C 50%% grey, F shifted blue for contrast with Cl).

GENERATED FILE - do not hand-edit values. Regenerated by gen_elements.py from
the upstream header (fetched 2026-07-30).
"""

ELEMENT_COUNT = %d

SYMBOLS = (
%s
)

NAMES = (
%s
)

# Standard atomic weights (amu).
MASSES = (
%s
)

# Van der Waals radii (Angstrom) - drives displayed sphere size.
RADII_VDW = (
%s
)

# Covalent radii (Angstrom) - drives bond perception.
RADII_COVALENT = (
%s
)

# Display colours, RGB 0-255.
COLORS = (
%s
)

_SYMBOL_TO_Z = {s.lower(): z for z, s in enumerate(SYMBOLS)}


def atomic_number(symbol):
    # type: (str) -> int
    """Atomic number for an element symbol; 0 (dummy) if unknown.

    Tolerant of case and trailing digits/labels ("C1", "cl2" -> 6, 17), the
    same convention ORCA Workbench's transform module uses."""
    letters = "".join(ch for ch in str(symbol) if ch.isalpha())
    if len(letters) >= 2:
        z = _SYMBOL_TO_Z.get(letters[:2].lower())
        if z:
            return z
    return _SYMBOL_TO_Z.get(letters[:1].lower(), 0)


def symbol(z):
    # type: (int) -> str
    return SYMBOLS[z] if 0 <= z < ELEMENT_COUNT else "Xx"


def name(z):
    # type: (int) -> str
    return NAMES[z] if 0 <= z < ELEMENT_COUNT else "Dummy"


def mass(z):
    # type: (int) -> float
    return MASSES[z] if 0 <= z < ELEMENT_COUNT else 0.0


def radius_vdw(z):
    # type: (int) -> float
    return RADII_VDW[z] if 0 <= z < ELEMENT_COUNT else 1.5


def radius_covalent(z):
    # type: (int) -> float
    return RADII_COVALENT[z] if 0 <= z < ELEMENT_COUNT else 1.5


def color(z):
    # type: (int) -> tuple
    """RGB 0-255 display colour."""
    return COLORS[z] if 0 <= z < ELEMENT_COUNT else COLORS[0]


def color_f(z):
    # type: (int) -> tuple
    """RGB 0.0-1.0 display colour (for GL)."""
    r, g, b = color(z)
    return (r / 255.0, g / 255.0, b / 255.0)
''' % (n,
       fmt_tuple_lines(sym_items, 10),
       fmt_tuple_lines(name_items, 5),
       fmt_tuple_lines(mass_items, 6),
       fmt_tuple_lines(vdw_items, 8),
       fmt_tuple_lines(cov_items, 8),
       fmt_tuple_lines(col_items, 4))

open(DST, "w", encoding="utf-8", newline="\n").write(py)
print("wrote", DST, "with", n, "elements")
